accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

reviews/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    movie_name = models.TextField()
    grade = models.IntegerField()
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)

reviews/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "title",
            "content",
            "movie_name",
            "grade",
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.save()  # ModelForm의 save 메서드의 리턴값은 해당 모델의 인스턴스다!
            auth_login(request, user)  # 로그인
            return redirect("reviews:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        # AuthenticationForm은 ModelForm이 아님!
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # 세션에 저장
            # login 함수는 request, user 객체를 인자로 받음
            # user 객체는 어디있어요? 바로 form에서 인증된 유저 정보를 받을 수 있음
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "reviews:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("reviews:index")

reviews/views.py
from django.shortcuts import render, redirect
from .forms import ReviewForm, CommentForm
from reviews.models import Review, Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    reviews = Review.objects.order_by("-pk")
    context = {
        "reviews": reviews,
    }
    return render(request, "reviews/index.html", context)


@login_required
def create(request):
    # title = request.POST.get("title")
    # content = request.POST.get("content")
    # Article.objects.create(title=title, content=content)
    # return redirect("articles:index")
    if request.method == "POST":
        # DB에 저장하는 로직
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect("reviews:create")
    else:
        review_form = ReviewForm()
    context = {
        "review_form": review_form,
    }
    return render(request, "reviews/new.html", context=context)


def detail(request, pk):
    # 특정 글을 가져온다.
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm()
    # template에 객체 전달
    context = {
        "review": review,
        "comments": review.comment_set.all(),
        "comment_form": comment_form,
    }
    return render(request, "reviews/detail.html", context)


@login_required
def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.user == review.user:
        if request.method == "POST":
            # POST : input 값 가져와서, 검증하고, DB에 저장
            review_form = ReviewForm(request.POST, request.FILES, instance=review)
            if review_form.is_valid():
                # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
                review_form.save()
                messages.success(request, "글이 수정되었습니다.")
                return redirect("reviews:detail", review.pk)
            # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 article_form을 랜더링
        else:
            # GET : Form을 제공
            review_form = ReviewForm(instance=review)
        context = {"review_form": review_form}
        return render(request, "reviews/form.html", context)
    else:
        # 작성자가 아닐 때
        # (1) 403 에러메시지를 던져버린다.
        # from django.http import HttpResponseForbidden
        # return HttpResponseForbidden()
        # (2) flash message 활용!
        messages.warning(request, "작성자만 수정할 수 있습니다.")
        return redirect("articles:detail", review.pk)


def delete(request, pk):
    # pk에 해당하는 글 삭제
    review = Review.objects.get(id=pk)
    review.delete()
    return redirect("reviews:index")


@login_required
def comment_create(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
    return redirect("reviews:detail", review.pk)


@login_required
def comment_delete(request, pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)

    if comment.user == request.user:
        comment.delete()
    return redirect("reviews:detail", pk)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block body %}
  <h1>로그인</h1>
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK"%}
  </form>
{% endblock body %}

accounts/templates/accounts/signup.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block body %}
  <h1>회원가입</h1>
  <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK"%}
  </form>

{% endblock body %}

pjt/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% bootstrap_css %}
    {% block css %}{% endblock css %}
  </head>

  <body>
    {% if request.user.is_authenticated %}
      <span>{{ request.user }}</span>
      <a href="{% url 'accounts:logout' %}">로그아웃</a>
    {% else %}
      <a href="{% url 'accounts:signup' %}">회원가입</a>
      <a href="{% url 'accounts:login' %}">로그인</a>
    {% endif %}

    <div class="container">
      {% block body %}{% endblock body %}
    </div>
  </body>

</html>

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block body %}
  <div>

    <h1>{{ review.title }}</h1>
    <h3>영화제목 :{{ review.movie_name }}</h3>
    <h3>영화내용 :
      {{ review.content }}</h3>
    <h3>평점 :
      {{ review.grade }}</h3>

    <a href="{% url 'reviews:update' review.pk %}">수정</a>
    <a href="{% url 'reviews:delete' review.pk %}">삭제</a>
  </div>
  <h4 class="my-3">댓글</h4>
  {% if request.user.is_authenticated %}

    <form action="{% url 'reviews:comment_create' review.pk %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form comment_form layout='inline'%}
      {% bootstrap_button button_type="submit" content="OK"%}
    </form>
    <hr>
    {% for comment in comments %}
      <p>
        {{ comment.user.username }}
        |
        {{ comment.content }}</p>
      <hr>
      <a href="{% url 'reviews:comment_delete' comment.review.pk comment.pk %}">삭제</a>
      {% empty %}
      <p>댓글이 없어요 ㅠ_ㅠ</p>
    {% endfor %}
  {% else %}
  {% endif %}
{% endblock %}
{% bootstrap_javascript %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block body %}
  <h1>게시판</h1>
  <table class="table">
    <thead>
      <tr class="table-warning">
        <th scope="col">아이디</th>
        <th scope="col">리뷰제목</th>
        <th scope="col">영화제목</th>
      </tr>
    </thead>
    {% for review in reviews %}
      <tbody>
        <tr class="table-warning">
          <td>{{ review.user }}</td>
          <td>
            <a href="{% url 'reviews:detail' review.pk %}">
              {{ review.title }}
            </a>
          </td>
          <td>{{ review.movie_name }}</td>
        </tr>
      </tbody>
    {% endfor %}
  </table>
{% endblock %}
{% bootstrap_javascript %}

reviews/templates/reviews/new.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block body %}
  <h1>글 쓰기</h1>

  <form action="{% url 'reviews:create' %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form review_form %}
    {% bootstrap_button button_type="submit" content="작성"%}
  </form>
{% endblock %}
</form>
{% bootstrap_javascript %}

reviews/templates/reviews/update.html
nes (18 sloc) 504 Bytes

{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}{% endblock %}
{% block body %}
  <h1>글 수정하기</h1>

  <form action="" method='post'>
    {% csrf_token %}
    {% bootstrap_form review_form %}
    {% bootstrap_button button_type="submit" content="수정"%}
  </form>
{% endblock %}
</form>
{% bootstrap_javascript %}